---

- name: Disable IPv6
  blockinfile:
    path: /etc/sysctl.conf
    block: |
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
      net.ipv6.conf.lo.disable_ipv6 = 1

- name: Execute sysctl -p on no-ASG instances
  shell: sysctl -p
