- name: Setup SSH Security hardening
  hosts: {{ host_param }}
  tags: ['security']
  become: yes
  tasks:
    - name: Disallow root SSH access
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PermitRootLogin"
                  line="PermitRootLogin no"
                  state=present
      notify: restart sshd

    - name: Disallow password SSH access
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication no"
                  state=present
      notify: restart sshd
  handlers:
    - name: restart sshd
      service: name=ssh state=restarted
